#!/bin/bash

cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_spu_attr.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_new_industry_v3_dense_outside.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_delay_delivery_time.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_creative_behavior_intention_keyword.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_ali_feature.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_dense_rewarded_pageid.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_user_level_photo_new.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_user_id_dup_cover_id.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_user_app_list_ad_app_id.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_reco_user_realtime_action_and_creative.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_querytoken_ad_campaign_type.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_longterm_action_cnt_ts_p5s_fix.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_like_author_id.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_follow_author_id_v1.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_callback_event_sparse.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_brand_user_combine_channel.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_product_name_dense.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_enhance_age.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_embedding_feature2.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_match_dense_num.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_live_user_merchant_list_online.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_live_realtime_detail_item.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_live_realtime_audience_count.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_item_goods_list.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_item_goods_id_list_size.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_realtime_action.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_live_mmu_class623.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_eshop_click_item_cate3_id.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_dense_ad_item_click_num.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_ad_playend_extend_short.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_ad_download_installed.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_universe_ad_.hount_target_cpm_pos.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_search_photo_asr.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_rtl_product_name_shallow_action_7d.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_reco_hate_photo.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_dpa_online_time.h ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_video_feature_moco_cluster.h ../teams/ad/ad_algorithm/bs_feature/fast/impl

cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_spu_attr.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_new_industry_v3_dense_outside.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_delay_delivery_time.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_creative_behavior_intention_keyword.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_ad_ali_feature.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_dense_rewarded_pageid.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_user_level_photo_new.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_user_id_dup_cover_id.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_user_app_list_ad_app_id.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_reco_user_realtime_action_and_creative.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_querytoken_ad_campaign_type.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_longterm_action_cnt_ts_p5s_fix.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_like_author_id.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_combine_follow_author_id_v1.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_callback_event_sparse.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_brand_user_combine_channel.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_product_name_dense.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_enhance_age.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_embedding_feature2.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_match_dense_num.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_live_user_merchant_list_online.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_live_realtime_detail_item.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_live_realtime_audience_count.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_item_goods_list.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_item_goods_id_list_size.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_realtime_action.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_live_mmu_class623.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_eshop_click_item_cate3_id.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_dense_ad_item_click_num.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_ad_playend_extend_short.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_ad_download_installed.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_universe_ad_account_target_cpm_pos.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_search_photo_asr.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_rtl_product_name_shallow_action_7d.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_user_reco_hate_photo.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_dpa_online_time.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
cp ../../ast/teams/ad/ad_algorithm/bs_feature/fast/impl/bs_extract_photo_video_feature_moco_cluster.cc ../teams/ad/ad_algorithm/bs_feature/fast/impl
